actions: add sweet-clang into playground

diff --git a/.github/workflows/playground.yml b/.github/workflows/playground.yml
--- a/.github/workflows/playground.yml
+++ b/.github/workflows/playground.yml
@@ -16,7 +16,7 @@ jobs:
       date: ${{ steps.ts.outputs.DATE }}
     strategy:
       matrix:
-        build-type: [sweet-pixelos, sweet-miui, mi89x7-community, a9y18qlte]
+        build-type: [sweet-pixelos, sweet-miui, sweet-clang, mi89x7-community, a9y18qlte]
         ksu-type: [zako, zako-susfs]
         bbg-type: [bbg, none]
         exclude:
@@ -45,6 +45,15 @@ jobs:
             ksu-type: zako
             bbg-type: bbg
           - build-type: sweet-miui
+            ksu-type: zako-susfs
+            bbg-type: none
+          - build-type: sweet-clang
+            ksu-type: zako
+            bbg-type: none
+          - build-type: sweet-clang
+            ksu-type: zako
+            bbg-type: bbg
+          - build-type: sweet-clang
             ksu-type: zako-susfs
             bbg-type: none
           - build-type: mi89x7-community
@@ -138,6 +147,16 @@ jobs:
             cp build.sh android_kernel_samsung_a9y18qlte/
             cp -r scripts android_kernel_samsung_a9y18qlte/
             chmod +x ./android_kernel_samsung_a9y18qlte/build.sh
+          elif [[ "${{ matrix.build-type }}" == "sweet-clang" ]]; then
+            if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
+              rm -rf android_kernel_xiaomi_sm6150
+            fi
+            echo "Cloning kernel sources..."
+            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6150
+            echo "Copying buildscript..."
+            cp build.sh android_kernel_xiaomi_sm6150/
+            cp -r scripts android_kernel_xiaomi_sm6150/
+            chmod +x ./android_kernel_xiaomi_sm6150/build.sh
           else
             echo "Invalid build type: ${{ matrix.build-type }}"
             exit 1
@@ -156,6 +175,10 @@ jobs:
             cd ..
           elif [[ "${{ matrix.build-type }}" == "a9y18qlte" ]]; then
             cd android_kernel_samsung_a9y18qlte/
+            ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }}
+            cd ..
+          elif [[ "${{ matrix.build-type }}" == "sweet-clang" ]]; then
+            cd android_kernel_xiaomi_sm6150/
             ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }}
             cd ..
           else
@@ -204,6 +227,16 @@ jobs:
               sed -i 's/device.name2=sweetin/device.name2=a9y18qltexx/' AnyKernel3/anykernel.sh
               sed -i 's/sweet (sm6150)/a9y18qlte (sdm660)/g' AnyKernel3/banner
             fi
+          elif [[ "${{ matrix.build-type }}" == "sweet-clang" ]]; then
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
+            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
+            if [[ "${{ matrix.build-type }}" == "sweet-clang" ]]; then
+              sed -i 's/device.name1=sweet/device.name1=sweet/' AnyKernel3/anykernel.sh
+              sed -i 's/device.name2=sweetin/device.name2=sweetin/' AnyKernel3/anykernel.sh
+              sed -i 's/sweet (sm6150)/sweet (sm6150)/g' AnyKernel3/banner
+            fi
           else
             echo "Invalid build type: ${{ matrix.build-type }}"
             exit 1
@@ -220,6 +253,11 @@ jobs:
             export ZIPNAME="Mi8937v2-${{ matrix.build-type }}-playground-${{ steps.ts.outputs.DATE }}.zip"
           elif [[ "${{ matrix.build-type }}" == "a9y18qlte" ]]; then
             export ZIPNAME="RiaruKernel-${{ matrix.build-type }}-playground-${{ steps.ts.outputs.DATE }}.zip"
+          elif [[ "${{ matrix.build-type }}" == "sweet-clang" ]]; then
+            export ZIPNAME="perf-neon-${{ matrix.build-type }}-playground-${{ steps.ts.outputs.DATE }}.zip"
+          else
+            echo "Invalid build type: ${{ matrix.build-type }}"
+            exit 1
           fi
           cd AnyKernel3
           zip -rq9 "../$ZIPNAME" ./*
@@ -266,7 +304,7 @@ jobs:
             > [!IMPORTANT]   
             > - This kernel only be used for playtesting purposes. Do NOT report bugs to the original author.   
             > - This kernel already includes ReSukiSU. Also SUSFS and Baseband Guard too, in exception of a9y18qlte.    
-            > - The Kernels that built with LTO enabled are sweet-miui and mi89x7-community.
+            > - The Kernels that built with LTO enabled are sweet-miui, sweet-clang and mi89x7-community.
 
             > [!CAUTION]   
             > - Always backup your boot & dtbo image first before proceeding!   
